"""
RetailSense AI — Customer ORM Model
=====================================
Defines the ``customers`` table, which is the central entity for all
customer-facing features: loyalty programmes, purchase history, AI-driven
segmentation, churn prediction, and recommendation engine.

Design decisions
-----------------
* UUID primary key — consistent with the ``users`` table; avoids sequential
  ID enumeration and is safe for distributed / sharded environments.
* ``email`` carries a unique constraint and a B-tree index for O(log n)
  lookups during checkout, loyalty look-up, and de-duplication imports.
* ``phone`` is *optional* — not all retail channels collect a phone number,
  but when present it must be unique (one customer per contact channel).
  An index is added to support fast look-ups by SMS/WhatsApp notifications.
* ``is_active`` enables soft-deletion; inactive customers are excluded from
  marketing campaigns and recommendation pipelines without losing history.
* ``TimestampMixin`` provides ``created_at`` / ``updated_at`` audit columns
  automatically (timezone-aware UTC).
* No FK to ``users`` here — the link between a staff/manager *user* and a
  *customer* record (e.g. who registered the customer) belongs in a future
  transaction/event model, not in this foundational entity.

Usage
-----
    from app.models.customer import Customer
"""

from __future__ import annotations

import uuid
from sqlalchemy import text

from sqlalchemy import Boolean, String, Index
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.database.session import Base
from app.models.base import TimestampMixin


# --------------------------------------------------------------------------- #
# Customer model                                                                #
# --------------------------------------------------------------------------- #

class Customer(TimestampMixin, Base):
    """SQLAlchemy ORM model for the ``customers`` table.

    Attributes
    ----------
    id : uuid.UUID
        Primary key. Generated by the database (``gen_random_uuid()``).
    first_name : str
        Customer's given name.  Max 150 characters.
    last_name : str
        Customer's family name.  Max 150 characters.
    email : str
        Unique contact email.  Max 320 characters (RFC 5321).
        Normalised to lower-case at the application layer (see schema).
        Carries a unique index for fast de-duplication and login look-ups.
    phone : str | None
        Optional phone number in E.164 format (e.g. ``+60123456789``).
        Unique when present; ``NULL`` values are *not* considered duplicates
        by PostgreSQL's unique index, so multiple customers may omit a phone.
    is_active : bool
        Soft-disable a customer without deleting their record.  Defaults to
        ``True``.  Inactive customers are excluded from campaigns and AI
        pipelines.
    notes : str | None
        Free-text field for staff to record customer preferences, allergies,
        or any other context.  Intentionally unstructured to keep the model
        lean; structured attributes belong in future profile tables.
    """

    __tablename__ = "customers"

    # ------------------------------------------------------------------ #
    # Primary key                                                          #
    # ------------------------------------------------------------------ #

    # UUID v4 generated by PostgreSQL — no application round-trip needed.
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=text("gen_random_uuid()"),
        nullable=False,
    )

    # ------------------------------------------------------------------ #
    # Identity fields                                                      #
    # ------------------------------------------------------------------ #

    first_name: Mapped[str] = mapped_column(
        String(150),
        nullable=False,
    )

    last_name: Mapped[str] = mapped_column(
        String(150),
        nullable=False,
    )

    # RFC 5321 maximum total email length is 320 characters.
    # unique=True creates a B-tree index implicitly; we also add an
    # explicit named index below so Alembic can generate a reliable DROP.
    email: Mapped[str] = mapped_column(
        String(320),
        unique=True,
        nullable=False,
        index=True,           # fast look-ups during checkout / import
    )

    # E.164 max length is 15 digits + '+' prefix = 16 chars; 20 gives a
    # comfortable margin for formatted variants during data entry.
    # nullable=True — phone is optional; unique constraint is NULLS NOT
    # DISTINCT-aware in PostgreSQL 15+ (NULLs treated as distinct, so
    # multiple rows may have NULL).
    phone: Mapped[str | None] = mapped_column(
        String(20),
        unique=True,          # one customer per phone when provided
        nullable=True,
        index=True,           # fast look-ups for SMS / notification flows
    )

    # ------------------------------------------------------------------ #
    # Status                                                               #
    # ------------------------------------------------------------------ #

    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        server_default="true",
    )

    # ------------------------------------------------------------------ #
    # Optional free-text notes                                            #
    # ------------------------------------------------------------------ #

    notes: Mapped[str | None] = mapped_column(
        String(1000),
        nullable=True,
    )

    # ------------------------------------------------------------------ #
    # Table-level indexes                                                  #
    # ------------------------------------------------------------------ #

    __table_args__ = (
        # Composite index supporting "search by name" queries that are
        # common in POS look-up flows (last_name first matches typical
        # retail search UX patterns).
        Index(
            "ix_customers_last_name_first_name",
            "last_name",
            "first_name",
        ),
    )

    # ------------------------------------------------------------------ #
    # Dunder helpers                                                       #
    # ------------------------------------------------------------------ #

    def __repr__(self) -> str:  # pragma: no cover
        return (
            f"<Customer id={self.id!s} "
            f"name={self.first_name!r} {self.last_name!r} "
            f"email={self.email!r}>"
        )
