"""
RetailSense AI — User ORM Model
=================================
Defines the ``users`` table and the ``UserRole`` enum used throughout the
application.

Design decisions
-----------------
* UUID primary key — avoids sequential ID enumeration attacks and is safe
  for distributed environments.
* ``UserRole`` is stored as a native PostgreSQL ENUM via SQLAlchemy's
  ``pgEnum``; this enforces the constraint at the database level.
* ``password_hash`` stores only the bcrypt digest — never the plain-text
  password.  The hashing itself is handled by the auth service layer.
* ``TimestampMixin`` provides ``created_at`` / ``updated_at`` automatically.

Usage
-----
    from app.models.user import User, UserRole
"""

from __future__ import annotations

import enum
import uuid
from sqlalchemy import text

from sqlalchemy import Boolean, Enum as pgEnum, String
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.database.session import Base
from app.models.base import TimestampMixin


# --------------------------------------------------------------------------- #
# Role enum                                                                     #
# --------------------------------------------------------------------------- #

class UserRole(str, enum.Enum):
    """Defines the access tiers available in the platform.

    Inheriting from ``str`` ensures the value is JSON-serialisable and
    can be compared directly to string literals without an extra ``.value``
    call.

    Levels
    ------
    ADMIN   — Full platform access; manage users and settings.
    MANAGER — Inventory, sales, and supplier management; read-only on users.
    STAFF   — Day-to-day operations: POS, stock checks, order fulfilment.
    """

    ADMIN = "admin"
    MANAGER = "manager"
    STAFF = "staff"


# --------------------------------------------------------------------------- #
# User model                                                                    #
# --------------------------------------------------------------------------- #

class User(TimestampMixin, Base):
    """SQLAlchemy ORM model for the ``users`` table.

    Attributes
    ----------
    id : uuid.UUID
        Primary key. Generated by the database (``gen_random_uuid()``).
    full_name : str
        Display name of the user.  Max 255 characters.
    email : str
        Unique email address used for login.  Stored in lower-case via
        application-level normalisation (see ``UserCreate`` schema).
    password_hash : str
        bcrypt digest of the user's password.  Never store plain text.
    role : UserRole
        Access tier.  Defaults to ``STAFF`` — least privilege principle.
    is_active : bool
        Soft-disable a user without deleting their record. Defaults to
        ``True``.  Inactive users are rejected during authentication.
    """

    __tablename__ = "users"

    # Primary key — UUID v4 generated by PostgreSQL
    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=text("gen_random_uuid()"),
        nullable=False,
    )

    full_name: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )

    email: Mapped[str] = mapped_column(
        String(320),          # RFC 5321 max email length
        unique=True,
        nullable=False,
        index=True,           # fast login lookups
    )

    password_hash: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )

    role: Mapped[UserRole] = mapped_column(
        pgEnum(
            UserRole,
            name="userrole",
            create_type=True,
            values_callable=lambda enum_cls: [e.value for e in enum_cls],
        ),
        nullable=False,
        default=UserRole.STAFF,
        server_default=text("'staff'"),
    )

    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        server_default="true",
    )

    # ---------------------------------------------------------------------- #
    # Dunder helpers                                                           #
    # ---------------------------------------------------------------------- #

    def __repr__(self) -> str:  # pragma: no cover
        return (
            f"<User id={self.id!s} email={self.email!r} role={self.role.value!r}>"
        )
